"""Add FRN status change history

Revision ID: 1687912b27de
Revises: 5a91abedf3eb
Create Date: 2026-03-26 01:27:47.862862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1687912b27de'
down_revision = '5a91abedf3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frn_status_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('form471_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form471_id'], ['form471s.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frn_status_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frn_status_changes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frn_status_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frn_status_changes_tenant_id'))

    op.drop_table('frn_status_changes')
    # ### end Alembic commands ###
