"""Add Form486, document-FRN link, school enrollment

Revision ID: 5a91abedf3eb
Revises: b94082026811
Create Date: 2026-03-25 21:55:18.654554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a91abedf3eb'
down_revision = 'b94082026811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form486s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('form471_id', sa.Integer(), nullable=True),
    sa.Column('funding_year', sa.Integer(), nullable=True),
    sa.Column('service_start_date', sa.Date(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form471_id'], ['form471s.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form486s', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form486s_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form471_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_documents_form471_id', 'form471s', ['form471_id'], ['id'])

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nslp_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('nslp_count')
        batch_op.drop_column('enrollment')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_form471_id', type_='foreignkey')
        batch_op.drop_column('form471_id')

    with op.batch_alter_table('form486s', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form486s_tenant_id'))

    op.drop_table('form486s')
    # ### end Alembic commands ###
