"""Make funding_year_id nullable on form470s and form471s

Revision ID: b94082026811
Revises: a345926f6781
Create Date: 2026-03-25 20:50:17.727912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94082026811'
down_revision = 'a345926f6781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form470s', schema=None) as batch_op:
        batch_op.alter_column('funding_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('form471s', schema=None) as batch_op:
        batch_op.alter_column('funding_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form471s', schema=None) as batch_op:
        batch_op.alter_column('funding_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('form470s', schema=None) as batch_op:
        batch_op.alter_column('funding_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
